---
excludes:
  scopes:
  - pattern: "dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
resolutions:
  rule_violations:
    - message: "NO_LICENSE_IN_DEPENDENCY - PyPI::(opentelemetry-exporter-otlp-proto-grpc|opentelemetry-semantic-conventions|opentelemetry-proto|aidial-sdk|opentelemetry-api|networkx|typer|typing-extensions|setuptools|httpx|fastapi|pygments|httpcore|starlette|idna|opentelemetry-exporter-prometheus|opentelemetry-exporter-otlp-proto-common|opentelemetry-sdk|typing-inspection|sentencepiece|scikit-learn|anyio|scipy|urllib3).*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "ORT cannot pick up license information for these packages with no clear license metadata"