{
 "title": "DIAL Analytics",
 "tags": [
  "DIAL",
  "ai-dial-analytics-realtime"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "influxdb3" }
  ]
 },
 "panels": [
  {
   "title": "Unique Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(DISTINCT user_hash)\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo;"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "SELECT\n  time AS _time,\n  COUNT(*) AS _value\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\n  AND _measurement = 'analytics'\n  AND _field = 'number_request_messages'\nGROUP BY time_bucket(INTERVAL '$__interval', time)\nORDER BY _time"
    }
   ]
  },
  {
   "title": "Stats Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT\n  project_id,\n  deployment,\n  model,\n  COUNT(DISTINCT user_hash) AS user_count,\n  COUNT(*) AS request_count,\n  SUM(COALESCE(prompt_tokens, 0)) AS prompt_tokens,\n  SUM(COALESCE(completion_tokens, 0)) AS completion_tokens,\n  SUM(COALESCE(price, 0.0)) AS money\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\nGROUP BY project_id, deployment, model"
    }
   ]
  },
  {
   "title": "Project Stats Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "SELECT\n  project_id,\n  COUNT(*) AS request_count,\n  SUM(COALESCE(prompt_tokens, 0)) AS prompt_tokens,\n  SUM(COALESCE(completion_tokens, 0)) AS completion_tokens,\n  SUM(COALESCE(price, 0.0)) AS money\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\nGROUP BY project_id"
    }
   ]
  },
  {
   "title": "Deployment/Model Stats Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "SELECT\n  \"model\",\n  \"deployment\",\n  COUNT(*) AS request_count,\n  SUM(COALESCE(\"prompt_tokens\", 0)) AS prompt_tokens,\n  SUM(COALESCE(\"completion_tokens\", 0)) AS completion_tokens,\n  SUM(COALESCE(\"price\", 0.0)) AS money\nFROM \"default\".\"analytics\"\nWHERE \"time\" >= $__timeFrom AND \"time\" < $__timeTo\nGROUP BY\n  \"model\",\n  \"deployment\""
    }
   ]
  }
 ]
}