{
 "title": "DIAL Analytics",
 "tags": [
  "DIAL",
  "ai-dial-analytics-realtime"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "influxdb" },
   { "name": "INFLUX_BUCKET", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Unique Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(DISTINCT user_hash)\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo;"
    }
   ]
  },
  {
   "title": "Popular Topics",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "query": "SELECT COUNT(*) AS count\nFROM analytics\nWHERE time >= v.timeRangeStart\n  AND time < v.timeRangeStop\n  AND _measurement = 'analytics'\n  AND _field = 'number_request_messages'\nGROUP BY topic"
    }
   ]
  },
  {
   "title": "Title-Topic Heatmap",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "SELECT COUNT(*) AS count\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\n  AND _measurement = 'analytics'\n  AND _field = 'number_request_messages'"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "SELECT\n  date_bin(INTERVAL '$__interval', time, TIMESTAMP '1970-01-01T00:00:00Z') AS _time,\n  COUNT(*) AS _value\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\n  AND _measurement = 'analytics'\n  AND _field = 'number_request_messages'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stats Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT\n  project_id,\n  deployment,\n  model,\n  COUNT(DISTINCT user_hash) AS user_count,\n  COUNT(*) AS request_count,\n  SUM(COALESCE(prompt_tokens, 0)) AS prompt_tokens,\n  SUM(COALESCE(completion_tokens, 0)) AS completion_tokens,\n  SUM(COALESCE(price, 0.0)) AS money\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\nGROUP BY project_id, deployment, model"
    }
   ]
  },
  {
   "title": "Project Stats Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "query": "SELECT\n  project_id,\n  COUNT(*) AS request_count,\n  SUM(COALESCE(prompt_tokens, 0)) AS prompt_tokens,\n  SUM(COALESCE(completion_tokens, 0)) AS completion_tokens,\n  SUM(COALESCE(price, 0.0)) AS money\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\nGROUP BY project_id"
    }
   ]
  },
  {
   "title": "Deployment/Model Stats Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "SELECT\n  model,\n  deployment,\n  COUNT(*) AS request_count,\n  SUM(COALESCE(prompt_tokens, 0)) AS prompt_tokens,\n  SUM(COALESCE(completion_tokens, 0)) AS completion_tokens,\n  SUM(COALESCE(price, 0.0)) AS money\nFROM analytics\nWHERE time >= $__timeFrom AND time < $__timeTo\nGROUP BY model, deployment"
    }
   ]
  }
 ]
}