from typing import Any, Dict, Protocol, Self, runtime_checkable


# Find the actual implementation in Python:
# https://github.com/influxdata/influxdb/blob/37ff7e6cd4598c312df3688026764a322969c1de/influxdb3_py_api/src/system_py.rs#L488-L613
@runtime_checkable
class LineBuilderProtocol(Protocol):
    def __init__(self, measurement: str) -> None: ...
    def time_ns(self, timestamp_ns: int) -> Self: ...
    def tag(self, key: str, value: str) -> Self: ...
    def string_field(self, key: str, value: str) -> Self: ...
    def int64_field(self, key: str, value: int) -> Self: ...
    def float64_field(self, key: str, value: float) -> Self: ...
    def bool_field(self, key: str, value: bool) -> Self: ...
    def build(self) -> str: ...


# Find the actual implementation in Rust:
# https://github.com/influxdata/influxdb/blob/37ff7e6cd4598c312df3688026764a322969c1de/influxdb3_py_api/src/system_py.rs#L203
@runtime_checkable
class InfluxDBClient(Protocol):
    def query(self, query: str) -> list[Dict[str, Any]]: ...
    def write_to_db(self, db_name: str, line: LineBuilderProtocol) -> None: ...
    def info(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
