from typing import Any, Dict, Protocol, Self, runtime_checkable


@runtime_checkable
class LineBuilderProtocol(Protocol):
    def __init__(self, measurement: str) -> None: ...
    def time_ns(self, timestamp_ns: int) -> Self: ...
    def tag(self, key: str, value: str) -> Self: ...
    def string_field(self, key: str, value: str) -> Self: ...
    def int64_field(self, key: str, value: int) -> Self: ...
    def float64_field(self, key: str, value: float) -> Self: ...
    def bool_field(self, key: str, value: bool) -> Self: ...
    def build(self) -> str: ...


@runtime_checkable
class InfluxDBClient(Protocol):
    def query(self, query: str) -> list[Dict[str, Any]]: ...
    def write_to_db(self, db_name: str, line: LineBuilderProtocol) -> None: ...
    def info(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
