image:
  pullPolicy: Always
  registry: registry-dev.deltixhub.com
  repository: ai/dial/application/dial-analytics
  tag: development
  pullSecrets:
    - epm-rtc-registry-dev


fullnameOverride: "dial-analytics"

containerSecurityContext:
  runAsUser: 1666

podSecurityContext:
  fsGroup: 1666

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

ingress:
  enabled: false

env:
  WEB_CONCURRENCY: "5"
