image:
  pullPolicy: Always
  registry: registry-test.deltixhub.com
  repository: ai/dial/application/dial-analytics
#  tag: development
  pullSecrets:
    - epm-rtc-registry-test


containerSecurityContext:
  runAsUser: 1001

podSecurityContext:
  fsGroup: 1001

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

ingress:
  enabled: false

env:
  INFLUX_URL: http://influxdb2.influxdb
  INFLUX_BUCKET: default
  INFLUX_ORG: deltix
